baseurl: "https://yopa.page/"
relativeURLs: true
languageCode: en-us
title: yopa.page
theme: "hugo-tania"
paginate: 8
googleAnalytics: ${{ secrets.GOOGLE_ANALYTICS_ID }}
uglyurls: true

params:
  titleLogo: images/08WeMC.png
  images:
    - images/8yRnin.png
  enableFootnotes: true
  siteName: yopa.page
  siteDesc: A blog providing how-to articles about development languages and the cloud.
  author: Yoonsoo Park
  maxCategoryToShow: 10
  socialOptions:
    email: yoonsoo@duck.com
    github: https://github.com/ypark9/how.wtf
    twitter: https://twitter.com/

# permalinks:
#   post: :title

menu:
  header:
    - name: About
      url: "/about.html"
    - name: Articles
      url: "/articles.html"
  footer:
    - name: About
      url: "/about.html"
    - name: Articles
      url: "/articles.html"
    - name: GitHub
      url: "https://github.com/ypark9/how.wtf"
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputs:
  home: ["HTML", "RSS", "JSON"]
